/**
 * The static site must be self-contained: every relative reference in the
 * HTML, and every relative import in the modules, points at a file in web/.
 * A typo here would otherwise only show up as a 404 on GitHub Pages.
 */
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { readdir, readFile } from 'node:fs/promises';
import { test } from 'node:test';

const WEB = new URL('../web/', import.meta.url);
const read = (name) => readFile(new URL(name, WEB), 'utf8');
const isRelative = (ref) => !/^(?:[a-z][a-z0-9+.-]*:|\/\/|#)/i.test(ref);
const resolves = (ref, from) => existsSync(new URL(ref.split(/[?#]/)[0], new URL(from, WEB)));

test('index.html only references files that exist', async () => {
  const html = await read('index.html');
  const refs = [...html.matchAll(/\s(?:href|src)="([^"]+)"/g)].map((m) => m[1]).filter(isRelative);
  assert.ok(refs.length >= 3, 'expected at least the stylesheet, script and icon');
  for (const ref of refs) assert.ok(resolves(ref, 'index.html'), `missing: ${ref}`);
});

test('index.html loads app.js as a module and nothing from other origins', async () => {
  const html = await read('index.html');
  assert.match(html, /<script type="module" src="\.\/app\.js"><\/script>/);
  const external = [...html.matchAll(/\s(?:src)="([^"]+)"/g)]
    .map((m) => m[1])
    .filter((r) => !isRelative(r));
  assert.deepEqual(external, []);
  assert.doesNotMatch(html, /<link[^>]+rel="stylesheet"[^>]+href="https?:/);
});

test('every relative import in web/*.js resolves', async () => {
  const files = (await readdir(WEB)).filter((f) => f.endsWith('.js'));
  assert.ok(files.includes('app.js') && files.includes('format.js'));
  for (const file of files) {
    const src = await read(file);
    const refs = [
      ...src.matchAll(/(?:import|export)\s[^'"]*?from\s+['"]([^'"]+)['"]/g),
      ...src.matchAll(/\bnew\s+Worker\(\s*['"]([^'"]+)['"]/g),
    ];
    for (const m of refs) {
      assert.ok(isRelative(m[1]), `${file}: non-relative import ${m[1]}`);
      assert.ok(resolves(m[1], file), `${file}: missing ${m[1]}`);
    }
  }
});

test('ids used by app.js exist in index.html', async () => {
  const [html, app] = await Promise.all([read('index.html'), read('app.js')]);
  const ids = new Set([...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]));
  const wanted = [
    ...[...app.matchAll(/\bel\('([^']+)'\)/g)].map((m) => m[1]),
    // Ids app.js builds or passes around rather than spelling out in el(...).
    ...[...app.matchAll(/\bmarkInvalid\('([^']+)'/g)].map((m) => `${m[1]}-error`),
    ...[...app.matchAll(/\bisPrefixOfOption\('([^']+)'/g)].map((m) => m[1]),
  ];
  assert.ok(wanted.includes('tz-error') && wanted.includes('tz-list'), 'extraction broke');
  for (const id of wanted) assert.ok(ids.has(id), `#${id} missing from index.html`);
});

test('form control names used by app.js exist in the form', async () => {
  // f.tz / form.elements.tz on a renamed input is `undefined.value` at run
  // time -- a dead page with every other test green.
  const [html, app] = await Promise.all([read('index.html'), read('app.js')]);
  const form = html.match(/<form[\s\S]*?<\/form>/)?.[0] ?? '';
  const names = new Set([...form.matchAll(/\sname="([^"]+)"/g)].map((m) => m[1]));
  // The preset radios are generated by app.js itself.
  names.add('preset');
  const used = new Set([...app.matchAll(/\b(?:f|form\.elements)\.(\w+)\b/g)].map((m) => m[1]));
  // Keys looked up dynamically: form.elements[key] over literal lists.
  for (const m of app.matchAll(/for \(const \w+ of (\[[^\]]+\])\) form\.elements\[/g)) {
    for (const [, key] of m[1].matchAll(/'(\w+)'/g)) used.add(key);
  }
  for (const m of app.matchAll(/for \(const name of (\[[^\]]+\])\) \{\s*form\.elements\[name\]/g)) {
    for (const [, key] of m[1].matchAll(/'(\w+)'/g)) used.add(key);
  }
  for (const key of ['preset', 'format', 'locale', 'tz', 'clock', 'seconds', 'prefix', 'suffix']) {
    assert.ok(used.has(key), `extraction broke: ${key} not seen in app.js`);
  }
  for (const name of used) assert.ok(names.has(name), `name="${name}" missing from the form`);
});

test('format.js stays pure (no DOM access)', async () => {
  const src = (await read('format.js')).replace(/\/\*[\s\S]*?\*\/|\/\/.*$/gm, '');
  assert.doesNotMatch(src, /\b(?:document|window|localStorage|location|navigator)\b/);
});
